import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronRight, Copy, Eye, FolderKanban, MousePointer2, Move, Plus, Redo2, Trash2, Undo2, X } from 'lucide-react';
import { initialElements, materials } from './data';
import { bendRadiusMm, developedLengthMm, type FenceElement, type Material } from './types';
import { DraggableCanvas } from './DraggableCanvas';

const euro=(v:number)=>new Intl.NumberFormat('sr-RS',{style:'currency',currency:'EUR'}).format(v);
const uid=()=>crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;

export function App(){
  const [entered,setEntered]=useState(false);
  if(!entered) return <WorkspaceHome onEnter={()=>setEntered(true)}/>;
  return <Workshop onExit={()=>setEntered(false)}/>;
}

function Brand(){return <div className="brand"><span className="logo">K</span><div><b>KOVAÄŚNICA</b><small>digitalna radionica</small></div></div>}

function Clock(){const [now,setNow]=useState(new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);const weekday=new Intl.DateTimeFormat('sr-Latn-RS',{weekday:'long'}).format(now);const date=new Intl.DateTimeFormat('sr-Latn-RS',{day:'2-digit',month:'short',year:'numeric'}).format(now);const time=now.toLocaleTimeString('sr-RS',{hour:'2-digit',minute:'2-digit'});const seconds=String(now.getSeconds()).padStart(2,'0');return <div className="forgeClock"><span className="forgeCalendar"><CalendarDays size={18}/></span><span className="forgeDate"><b>{weekday}</b><small>{date}</small></span><span className="forgeTime"><strong>{time}</strong><i>{seconds}</i></span></div>}

function WorkspaceHome({onEnter}:{onEnter:()=>void}){
 const [active,setActive]=useState(false); const [pin,setPin]=useState(''); const [error,setError]=useState('');
 const open=()=>{if(pin==='1234')onEnter();else setError('PogreĹˇan PIN. PokuĹˇajte ponovo.')};
 return <main className="workspaceHome"><nav className="homeNav"><Brand/><div><Clock/><button className="homeAvatar">VM</button></div></nav><div className="signalBar"><i/><div><span>KOVAÄŚNICA</span><span>KOVAÄŚNICA</span></div><i/></div><section className="homeContent"><div className="homeIntro"><div><small>VAĹ E RADIONICE</small><h1>Dobro doĹˇli u KOVAÄŚNICU</h1><p>Izaberite radionicu ili dodajte novi radni prostor.</p></div><div className="workspaceCount"><b>1</b><span>aktivna radionica</span></div></div><div className="sectionLine"><span/><b>RADNI PROSTORI</b><i>6 MJESTA</i></div><div className="workspaceGrid"><button className="workspaceCard populated" onClick={()=>{setActive(true);setError('')}}><div className="cardLines"><i/><i/><i/></div><div className="cardTop"><span className="workspaceIcon">K</span><span className="statusDot"><i/> AKTIVNA</span></div><div className="cardCopy"><small>RADIONICA</small><h2>KOVAC</h2><p>Vladimir MitiÄ‡</p></div><div className="cardFoot"><span>Otvori radionicu</span><ChevronRight size={18}/></div></button>{Array.from({length:5},(_,i)=><button className="workspaceCard addCard" key={i}><span className="slotNumber">0{i+2}</span><span className="addIcon"><Plus size={24}/></span><b>Dodaj radionicu</b><p>Kreirajte novi prostor za projekte</p></button>)}</div><div className="homeNote"><FolderKanban size={17}/><span>Svaka radionica ima zasebne projekte, materijale i podeĹˇavanja.</span></div></section>{active&&<div className="modalBack" onMouseDown={()=>setActive(false)}><form className="accessModal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();open()}}><button type="button" className="close" onClick={()=>setActive(false)}><X/></button><span className="workspaceIcon large">K</span><small>ULAZ U RADIONICU</small><h2>KOVAC</h2><p>Vladimir MitiÄ‡</p><label>Pristupni PIN<input autoFocus value={pin} onChange={e=>setPin(e.target.value)} type="password" placeholder="Unesite PIN"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide">Otvori radionicu <ChevronRight size={18}/></button></form></div>}</main>
}

function Workshop({onExit}:{onExit:()=>void}){
 const [els,setEls]=useState<FenceElement[]>(initialElements); const [selected,setSelected]=useState('frame-top'); const [tab,setTab]=useState('Konstrukcija'); const [modal,setModal]=useState<'preview'|'finish'|'calc'|null>(null);
 const current=els.find(e=>e.id===selected); const total=useMemo(()=>els.reduce((s,e)=>s+developedLengthMm(e)/1000*e.pricePerMeter,0),[els]); const meters=els.reduce((s,e)=>s+developedLengthMm(e),0)/1000;
 const update=(patch:Partial<FenceElement>)=>setEls(v=>v.map(e=>e.id===selected?{...e,...patch}:e));
 const add=(m:Material)=>{const n:FenceElement={id:uid(),type:'profile',materialCode:m.code,name:m.name,size:m.size,lengthMm:1000,orientation:'vertical',positionX:1450,positionY:400,pricePerMeter:m.pricePerMeter};setEls(v=>[...v,n]);setSelected(n.id)};
 const duplicate=()=>{if(!current)return;const n={...current,id:uid(),positionX:Math.min(2960,current.positionX+80),positionY:Math.min(1760,current.positionY+80)};setEls(v=>[...v,n]);setSelected(n.id)};
 const remove=()=>{if(!current)return;setEls(v=>v.filter(e=>e.id!==current.id));setSelected('')};
 return <div className="appShell"><header><Brand/><div className="project"><small>TRENUTNI PROJEKAT</small><strong>Ulazna ograda â€“ Horvat</strong></div><span className="saved"><Check size={14}/> Sve izmene saÄŤuvane</span><div className="headerActions"><button onClick={()=>setModal('preview')}><Eye size={17}/> Pregled</button><button className="primary" onClick={()=>setModal('finish')}><Check size={17}/> ZavrĹˇi projekat</button><button className="avatar" title="Izlaz" onClick={onExit}>MH</button></div></header>
 <div className="work"><aside className="library"><div className="tabs">{['Konstrukcija','Ukrasi','Okov'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Konstrukcija'?<><div className="asideTitle"><span>PROFILI I Ĺ IPKE</span><small>{materials.length} elementa</small></div><div className="materialList">{materials.map(m=><button className="material" key={m.code} onClick={()=>add(m)}><Cross shape={m.shape}/><span><b>{m.name}</b><small>{m.size} Â· {m.code}</small></span><strong>{m.pricePerMeter.toFixed(2).replace('.',',')} â‚¬<small>/m</small></strong></button>)}</div><p className="hint">Kliknite na materijal da ga dodate na radnu povrĹˇinu.</p></>:<div className="empty"><div>â—‡</div><b>Biblioteka u pripremi</b><p>Stvarni SVG elementi biÄ‡e dodati u sledeÄ‡oj fazi.</p></div>}</aside>
 <section className="stage"><div className="toolbar"><button className="active"><MousePointer2 size={17}/> Izbor</button><button className="moveReady"><Move size={17}/> Povuci profil</button><i/><button onClick={duplicate} disabled={!current}><Copy size={17}/></button><button onClick={remove} disabled={!current}><Trash2 size={17}/></button><i/><button disabled><Undo2 size={17}/></button><button disabled><Redo2 size={17}/></button><span>Prednji pogled</span><small>3.000 Ă— 1.800 mm</small></div><DraggableCanvas els={els} selected={selected} setSelected={setSelected} updateElement={(id,positionX,positionY)=>setEls(v=>v.map(e=>e.id===id?{...e,positionX,positionY}:e))}/></section>
 <aside className="properties"><div className="panelHead"><div><small>IZABRANI ELEMENT</small><h2>{current?.name??'Nema izbora'}</h2></div><span>{current?.materialCode??'â€”'}</span></div>{current?<><div className="section"><label>Dimenzija profila<div className="readonly">{current.size}</div></label><label>DuĹľina <span>mm</span><input type="number" min="50" max="6000" value={current.lengthMm} onChange={e=>update({lengthMm:+e.target.value})}/></label><label>Orijentacija<div className="segmented"><button className={current.orientation==='horizontal'?'active':''} onClick={()=>update({orientation:'horizontal'})}>Vodoravno</button><button className={current.orientation==='vertical'?'active':''} onClick={()=>update({orientation:'vertical'})}>Uspravno</button></div></label><BendControls item={current} onUpdate={update}/><div className="coords"><label>PoloĹľaj X <span>mm</span><input type="number" value={current.positionX} onChange={e=>update({positionX:+e.target.value})}/></label><label>PoloĹľaj Y <span>mm</span><input type="number" value={current.positionY} onChange={e=>update({positionY:+e.target.value})}/></label></div><PrecisionControls item={current} onUpdate={update}/><div className="row"><button onClick={duplicate}><Copy size={15}/> Dupliraj</button><button className="danger" onClick={remove}><Trash2 size={15}/> ObriĹˇi</button></div></div><div className="cost"><small>OBRAÄŚUN ELEMENTA</small><p><span>MetraĹľa</span><b>{(developedLengthMm(current)/1000).toFixed(2)} m</b></p><p><span>Cena po metru</span><b>{euro(current.pricePerMeter)}</b></p><p className="sum"><span>Ukupno</span><b>{euro(developedLengthMm(current)/1000*current.pricePerMeter)}</b></p></div></>:<div className="empty"><p>Izaberite element na crteĹľu.</p></div>}</aside></div>
 <footer><div><small>UKUPNA METRAĹ˝A</small><b>{meters.toFixed(2)} m</b></div><div><small>POSTAVLJENI DELOVI</small><b>{els.length}</b></div><div><small>PROCENA MATERIJALA</small><b className="blue">{euro(total)}</b></div><button onClick={()=>setModal('calc')}>Otvori obraÄŤun <ChevronRight size={17}/></button></footer>{modal&&<Modal kind={modal} els={els} total={total} close={()=>setModal(null)}/>}</div>
}

function PrecisionControls({item,onUpdate}:{item:FenceElement;onUpdate:(patch:Partial<FenceElement>)=>void}){
 const thickness=Number(item.size.match(/\d+/)?.[0]??40); const rise=item.shape==='arc'?Math.max(0,item.bendRiseMm??0):0;
 const maxX=Math.max(0,3000-(item.orientation==='horizontal'?item.lengthMm:thickness+rise));
 const maxY=Math.max(0,1800-(item.orientation==='vertical'?item.lengthMm:thickness+rise));
 const move=(dx:number,dy:number)=>onUpdate({positionX:Math.max(0,Math.min(maxX,item.positionX+dx)),positionY:Math.max(0,Math.min(maxY,item.positionY+dy))});
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.target as HTMLElement).matches('input, textarea, select'))return;const step=event.shiftKey?10:1;const directions:Record<string,[number,number]>={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]};const direction=directions[event.key];if(direction){event.preventDefault();move(...direction)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 return <div className="precisionMove"><div className="precisionTitle"><b>PRECIZNO POMERANJE</b><span>korak 1 mm</span></div><div className="nudge"><button title="Levo 1 mm" onClick={()=>move(-1,0)}>←</button><button title="Gore 1 mm" onClick={()=>move(0,-1)}>↑</button><button title="Dole 1 mm" onClick={()=>move(0,1)}>↓</button><button title="Desno 1 mm" onClick={()=>move(1,0)}>→</button></div><div className="centerControls"><button onClick={()=>onUpdate({positionX:Math.round(maxX/2)})}>Centriraj X</button><button onClick={()=>onUpdate({positionY:Math.round(maxY/2)})}>Centriraj Y</button></div><small>Strelice na tastaturi: 1 mm · Shift: 10 mm</small></div>
}

function BendControls({item,onUpdate}:{item:FenceElement;onUpdate:(patch:Partial<FenceElement>)=>void}){
 const curved=item.shape==='arc'; const maxRise=Math.max(10,Math.min(1500,item.lengthMm/2)); const rise=Math.min(maxRise,Math.max(10,item.bendRiseMm??300)); const developed=developedLengthMm({...item,shape:curved?'arc':'straight',bendRiseMm:rise}); const radius=bendRadiusMm({...item,shape:'arc',bendRiseMm:rise});
 return <div className="bendControls"><div className="precisionTitle"><b>OBLIK I ROTACIJA</b><span>{curved?'savijeni profil':'ravni profil'}</span></div><button className="rotateProfile" onClick={()=>onUpdate({orientation:item.orientation==='horizontal'?'vertical':'horizontal'})}>↻ Rotiraj profil 90°</button><div className="shapeSwitch"><button className={!curved?'active':''} onClick={()=>onUpdate({shape:'straight'})}>Ravan</button><button className={curved?'active':''} onClick={()=>onUpdate({shape:'arc',bendRiseMm:rise})}>Luk</button></div>{curved&&<><label>Visina luka <span>mm</span><input type="number" min="10" max={maxRise} step="1" value={rise} onChange={event=>onUpdate({bendRiseMm:Math.min(maxRise,Math.max(10,+event.target.value))})}/></label><div className="bendNudge"><button onClick={()=>onUpdate({bendRiseMm:Math.max(10,rise-10)})}>−10 mm</button><button onClick={()=>onUpdate({bendRiseMm:Math.min(maxRise,rise+10)})}>+10 mm</button></div><div className="bendMetrics"><p><span>Raspon</span><b>{item.lengthMm} mm</b></p><p><span>Radijus</span><b>{Math.round(radius)} mm</b></p><p><span>Razvijena dužina</span><b>{Math.round(developed)} mm</b></p></div></>}</div>
}

function Cross({shape}:{shape:Material['shape']}){return <span className={`cross ${shape}`}><i/></span>}
function Canvas({els,selected,setSelected,updateElement}:{els:FenceElement[];selected:string;setSelected:(v:string)=>void;updateElement:(id:string,x:number,y:number)=>void}){
 const [drag,setDrag]=useState<{id:string;pointerId:number;offsetX:number;offsetY:number}|null>(null);
 const position=(event:React.PointerEvent<HTMLDivElement>,item:FenceElement)=>{const rect=event.currentTarget.getBoundingClientRect();const rawX=(event.clientX-rect.left)/rect.width*3000-(drag?.offsetX??0);const rawY=(event.clientY-rect.top)/rect.height*1800-(drag?.offsetY??0);const thickness=Number(item.size.match(/\d+/)?.[0]??40);const maxX=3000-(item.orientation==='horizontal'?item.lengthMm:thickness);const maxY=1800-(item.orientation==='vertical'?item.lengthMm:thickness);updateElement(item.id,Math.round(Math.max(0,Math.min(maxX,rawX))),Math.round(Math.max(0,Math.min(maxY,rawY))))};
 return <div className="canvasWrap"><div className="ruler top">{[0,500,1000,1500,2000,2500,3000].map(n=><span key={n}>{n}</span>)}</div><div className="ruler side">{[0,300,600,900,1200,1500,1800].map(n=><span key={n}>{n}</span>)}</div><div className={`canvas ${drag?'dragging':''}`} onClick={()=>setSelected('')} onPointerMove={event=>{if(!drag)return;const item=els.find(e=>e.id===drag.id);if(item)position(event,item)}} onPointerUp={event=>{if(drag?.pointerId===event.pointerId){event.currentTarget.releasePointerCapture(event.pointerId);setDrag(null)}}} onPointerCancel={()=>setDrag(null)}><div className="dimension width"><span>3.000 mm</span></div><div className="dimension height"><span>1.800 mm</span></div>{els.map(e=>{const hor=e.orientation==='horizontal';return <button aria-label={`${e.name} ${e.lengthMm} mm`} key={e.id} onClick={x=>x.stopPropagation()} onPointerDown={event=>{event.stopPropagation();setSelected(e.id);const canvas=event.currentTarget.parentElement!;const rect=canvas.getBoundingClientRect();const pointerX=(event.clientX-rect.left)/rect.width*3000;const pointerY=(event.clientY-rect.top)/rect.height*1800;canvas.setPointerCapture(event.pointerId);setDrag({id:e.id,pointerId:event.pointerId,offsetX:pointerX-e.positionX,offsetY:pointerY-e.positionY})}} className={`beam ${selected===e.id?'selected':''} ${drag?.id===e.id?'isDragging':''}`} style={{left:`${e.positionX/3000*100}%`,top:`${e.positionY/1800*100}%`,width:hor?`${e.lengthMm/3000*100}%`:'10px',height:hor?'10px':`${e.lengthMm/1800*100}%`}}><span>{selected===e.id?`${e.lengthMm} mm Â· X ${e.positionX} Â· Y ${e.positionY}`:''}</span></button>})}</div></div>}
function Modal({kind,els,total,close}:{kind:string;els:FenceElement[];total:number;close:()=>void}){const grouped=materials.map(m=>({m,list:els.filter(e=>e.materialCode===m.code)})).filter(x=>x.list.length);return <div className="modalBack" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="logo">K</span><h2>{kind==='preview'?'Pregled projekta':kind==='finish'?'Projekat je spreman za zavrĹˇnu obradu':'Trenutni obraÄŤun'}</h2><p>{kind==='finish'?'Komponenta za zavrĹˇni rezultat je pripremljena. TehniÄŤki crteĹľ, optimizacija Ĺˇipki i PDF ponuda biÄ‡e oblikovani nakon odobrenja osnovnog ekrana.':'Ulazna ograda â€“ Horvat Â· 3.000 Ă— 1.800 mm'}</p>{kind!=='finish'&&<div className="bill">{grouped.map(({m,list})=><div key={m.code}><span>{m.name} {m.size}<small>{list.length} kom Â· {(list.reduce((s,e)=>s+developedLengthMm(e),0)/1000).toFixed(2)} m</small></span><b>{euro(list.reduce((s,e)=>s+developedLengthMm(e)/1000*e.pricePerMeter,0))}</b></div>)}<div className="billTotal"><span>Procena materijala</span><b>{euro(total)}</b></div></div>}<button className="primary wide" onClick={close}>Nazad u radionicu</button></div></div>}
