import { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Copy, Eye, LogOut, MousePointer2, Move, Redo2, RotateCcw, Trash2, Undo2, X } from 'lucide-react';
import { initialElements, materials } from './data';
import type { FenceElement, Material, Orientation } from './types';

const euro=(v:number)=>new Intl.NumberFormat('sr-RS',{style:'currency',currency:'EUR'}).format(v);
const uid=()=>crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;

export function App(){
  const [entered,setEntered]=useState(false);
  const [code,setCode]=useState(''); const [pin,setPin]=useState(''); const [error,setError]=useState('');
  if(!entered) return <Login code={code} pin={pin} setCode={setCode} setPin={setPin} error={error} onEnter={()=>{if(code.toUpperCase()==='KOVAC-001'&&pin==='1234')setEntered(true);else setError('Proverite šifru radionice i PIN.');}}/>;
  return <Workshop onExit={()=>{setEntered(false);setPin('');}}/>;
}

function Brand(){return <div className="brand"><span className="logo">K</span><div><b>KOVAČNICA</b><small>digitalna radionica</small></div></div>}

function Login({code,pin,setCode,setPin,error,onEnter}:{code:string;pin:string;setCode:(v:string)=>void;setPin:(v:string)=>void;error:string;onEnter:()=>void}){
 return <main className="login"><div className="loginGlow"/><form className="loginCard" onSubmit={e=>{e.preventDefault();onEnter()}}><Brand/><div className="loginCopy"><h1>Dobro došli u radionicu</h1><p>Digitalna radionica za projektovanje ograda</p></div><label>Šifra radionice<input autoFocus value={code} onChange={e=>setCode(e.target.value)} placeholder="npr. KOVAC-001"/></label><label>Pristupni PIN<input value={pin} onChange={e=>setPin(e.target.value)} type="password" placeholder="Unesite PIN"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide">Otvori radionicu <ChevronRight size={18}/></button><small className="secure">Zaštićen pristup vašem radnom prostoru</small></form></main>
}

function Workshop({onExit}:{onExit:()=>void}){
 const [els,setEls]=useState<FenceElement[]>(initialElements); const [selected,setSelected]=useState('frame-top'); const [tab,setTab]=useState('Konstrukcija'); const [modal,setModal]=useState<'preview'|'finish'|'calc'|null>(null);
 const current=els.find(e=>e.id===selected); const total=useMemo(()=>els.reduce((s,e)=>s+e.lengthMm/1000*e.pricePerMeter,0),[els]); const meters=els.reduce((s,e)=>s+e.lengthMm,0)/1000;
 const update=(patch:Partial<FenceElement>)=>setEls(v=>v.map(e=>e.id===selected?{...e,...patch}:e));
 const add=(m:Material)=>{const n:FenceElement={id:uid(),type:'profile',materialCode:m.code,name:m.name,size:m.size,lengthMm:1000,orientation:'vertical',positionX:1450,positionY:400,pricePerMeter:m.pricePerMeter};setEls(v=>[...v,n]);setSelected(n.id)};
 const duplicate=()=>{if(!current)return;const n={...current,id:uid(),positionX:Math.min(2960,current.positionX+80),positionY:Math.min(1760,current.positionY+80)};setEls(v=>[...v,n]);setSelected(n.id)};
 const remove=()=>{if(!current)return;setEls(v=>v.filter(e=>e.id!==current.id));setSelected('')};
 return <div className="appShell"><header><Brand/><div className="project"><small>TRENUTNI PROJEKAT</small><strong>Ulazna ograda – Horvat</strong></div><span className="saved"><Check size={14}/> Sve izmene sačuvane</span><div className="headerActions"><button onClick={()=>setModal('preview')}><Eye size={17}/> Pregled</button><button className="primary" onClick={()=>setModal('finish')}><Check size={17}/> Završi projekat</button><button className="avatar" title="Izlaz" onClick={onExit}>MH</button></div></header>
 <div className="work"><aside className="library"><div className="tabs">{['Konstrukcija','Ukrasi','Okov'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Konstrukcija'?<><div className="asideTitle"><span>PROFILI I ŠIPKE</span><small>{materials.length} elementa</small></div><div className="materialList">{materials.map(m=><button className="material" key={m.code} onClick={()=>add(m)}><Cross shape={m.shape}/><span><b>{m.name}</b><small>{m.size} · {m.code}</small></span><strong>{m.pricePerMeter.toFixed(2).replace('.',',')} €<small>/m</small></strong></button>)}</div><p className="hint">Kliknite na materijal da ga dodate na radnu površinu.</p></>:<div className="empty"><div>◇</div><b>Biblioteka u pripremi</b><p>Stvarni SVG elementi biće dodati u sledećoj fazi.</p></div>}</aside>
 <section className="stage"><div className="toolbar"><button className="active"><MousePointer2 size={17}/> Izbor</button><button><Move size={17}/> Pomeranje</button><i/><button onClick={duplicate} disabled={!current}><Copy size={17}/></button><button onClick={remove} disabled={!current}><Trash2 size={17}/></button><i/><button disabled><Undo2 size={17}/></button><button disabled><Redo2 size={17}/></button><span>Prednji pogled</span><small>3.000 × 1.800 mm</small></div><Canvas els={els} selected={selected} setSelected={setSelected}/></section>
 <aside className="properties"><div className="panelHead"><div><small>IZABRANI ELEMENT</small><h2>{current?.name??'Nema izbora'}</h2></div><span>{current?.materialCode??'—'}</span></div>{current?<><div className="section"><label>Dimenzija profila<div className="readonly">{current.size}</div></label><label>Dužina <span>mm</span><input type="number" min="50" max="6000" value={current.lengthMm} onChange={e=>update({lengthMm:+e.target.value})}/></label><label>Orijentacija<div className="segmented"><button className={current.orientation==='horizontal'?'active':''} onClick={()=>update({orientation:'horizontal'})}>Vodoravno</button><button className={current.orientation==='vertical'?'active':''} onClick={()=>update({orientation:'vertical'})}>Uspravno</button></div></label><div className="coords"><label>Položaj X <span>mm</span><input type="number" value={current.positionX} onChange={e=>update({positionX:+e.target.value})}/></label><label>Položaj Y <span>mm</span><input type="number" value={current.positionY} onChange={e=>update({positionY:+e.target.value})}/></label></div><div className="nudge"><button onClick={()=>update({positionX:current.positionX-10})}>←</button><button onClick={()=>update({positionY:current.positionY-10})}>↑</button><button onClick={()=>update({positionY:current.positionY+10})}>↓</button><button onClick={()=>update({positionX:current.positionX+10})}>→</button></div><div className="row"><button onClick={duplicate}><Copy size={15}/> Dupliraj</button><button className="danger" onClick={remove}><Trash2 size={15}/> Obriši</button></div></div><div className="cost"><small>OBRAČUN ELEMENTA</small><p><span>Metraža</span><b>{(current.lengthMm/1000).toFixed(2)} m</b></p><p><span>Cena po metru</span><b>{euro(current.pricePerMeter)}</b></p><p className="sum"><span>Ukupno</span><b>{euro(current.lengthMm/1000*current.pricePerMeter)}</b></p></div></>:<div className="empty"><p>Izaberite element na crtežu.</p></div>}</aside></div>
 <footer><div><small>UKUPNA METRAŽA</small><b>{meters.toFixed(2)} m</b></div><div><small>POSTAVLJENI DELOVI</small><b>{els.length}</b></div><div><small>PROCENA MATERIJALA</small><b className="blue">{euro(total)}</b></div><button onClick={()=>setModal('calc')}>Otvori obračun <ChevronRight size={17}/></button></footer>{modal&&<Modal kind={modal} els={els} total={total} close={()=>setModal(null)}/>}</div>
}

function Cross({shape}:{shape:Material['shape']}){return <span className={`cross ${shape}`}><i/></span>}
function Canvas({els,selected,setSelected}:{els:FenceElement[];selected:string;setSelected:(v:string)=>void}){return <div className="canvasWrap"><div className="ruler top">{[0,500,1000,1500,2000,2500,3000].map(n=><span key={n}>{n}</span>)}</div><div className="ruler side">{[0,300,600,900,1200,1500,1800].map(n=><span key={n}>{n}</span>)}</div><div className="canvas" onClick={()=>setSelected('')}><div className="dimension width"><span>3.000 mm</span></div><div className="dimension height"><span>1.800 mm</span></div>{els.map(e=>{const hor=e.orientation==='horizontal';return <button aria-label={`${e.name} ${e.lengthMm} mm`} key={e.id} onClick={x=>{x.stopPropagation();setSelected(e.id)}} className={`beam ${selected===e.id?'selected':''}`} style={{left:`${e.positionX/3000*100}%`,top:`${e.positionY/1800*100}%`,width:hor?`${e.lengthMm/3000*100}%`:'10px',height:hor?'10px':`${e.lengthMm/1800*100}%`}}><span>{selected===e.id?`${e.lengthMm} mm`:''}</span></button>})}</div></div>}
function Modal({kind,els,total,close}:{kind:string;els:FenceElement[];total:number;close:()=>void}){const grouped=materials.map(m=>({m,list:els.filter(e=>e.materialCode===m.code)})).filter(x=>x.list.length);return <div className="modalBack" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="logo">K</span><h2>{kind==='preview'?'Pregled projekta':kind==='finish'?'Projekat je spreman za završnu obradu':'Trenutni obračun'}</h2><p>{kind==='finish'?'Komponenta za završni rezultat je pripremljena. Tehnički crtež, optimizacija šipki i PDF ponuda biće oblikovani nakon odobrenja osnovnog ekrana.':'Ulazna ograda – Horvat · 3.000 × 1.800 mm'}</p>{kind!=='finish'&&<div className="bill">{grouped.map(({m,list})=><div key={m.code}><span>{m.name} {m.size}<small>{list.length} kom · {(list.reduce((s,e)=>s+e.lengthMm,0)/1000).toFixed(2)} m</small></span><b>{euro(list.reduce((s,e)=>s+e.lengthMm/1000*e.pricePerMeter,0))}</b></div>)}<div className="billTotal"><span>Procena materijala</span><b>{euro(total)}</b></div></div>}<button className="primary wide" onClick={close}>Nazad u radionicu</button></div></div>}
